spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: sam@1996
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        show_sql: false

  # mail server configurations
  mail:
    host: smtp.gmail.com
    password: paynfvzogmfnnckf
    port: 587
    username: kimucredit@gmail.com
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true