spring:
  datasource:
    url: jdbc:mysql://fesd70apbgx0iiit:jnshebjn0huussh1@r4919aobtbi97j46.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/o1i7e7szy30id6zw
    username: fesd70apbgx0iiit
    password: jnshebjn0huussh1
    hikari:
      maximum-pool-size: 30       # Adjust as necessary within your limit
      idle-timeout: 10000         # 10 seconds
      max-lifetime: 30000         # 30 seconds
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        show_sql: false


  # mail server configurations
  mail:
    host: smtp.gmail.com
    password: paynfvzogmfnnckf
    port: 587
    username: kimucredit@gmail.com
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true